### ISSUE TITLE
All blocks are invisible.  

### ISSUE THREAD

**Issue by Cayden2606** [depressed-pho/natural-mystic-shaders#79] opened 2020-05-04 10:03 UTC
All blocks are invisible. I uninstall and install the mcpack and nothing changed.
![Screenshot_20200504-175918_Minecraft](https://user-images.githubusercontent.com/64778893/80955232-84c0f000-8e31-11ea-9fdd-bd6c1615cdd0.jpg)
![Uploading Screenshot_20200504-175814_Minecraft.jpg…]()

**Comment by depressed-pho** [comment] 2020-07-17 13:15
That happens when the game fails to load my terrain shader. In the past the game just crashed while loading, but now it replaces unloadable shaders with one which renders nothing.

The problem is that the game doesn't show any errors that occur while loading shaders, which means I have no idea why it doesn't load on certain devices. Maybe you have an Android phone?

**Comment by depressed-pho** [comment] 2020-07-17 13:51
This ticket is a duplicate of #73. Closing.

**Closed by depressed-pho** 2020-07-17 13:51 UTC
Labels: cannot reproduce
