### ISSUE TITLE
Dark stuff

### ISSUE THREAD

**Issue by gio1135** [depressed-pho/natural-mystic-shaders#68] opened 2019-02-25 05:55 UTC
So when I made the torches whiter and brighter, and the night time brighter, things like chests, beds, crafting tables, and such are kinda dark. It looks odd. How do I fix that?
— Sincerely, n00b

**Comment by depressed-pho** [comment] 2019-02-27 04:34
Those things are rendered by an entity shader which is still unmodified in my shader pack (#54). To change how they are rendered, you need to modify its code! There's no configuration values for it yet.

**Comment by depressed-pho** [comment] 2019-02-27 04:35
I'm closing this issue as it's basically a dupe of #54.

**Closed by depressed-pho** 2019-02-27 04:35 UTC

**Comment by gio1135** [comment] 2019-02-27 06:05
Oh, okie. Thanks my favorite depressed boi.
