### ISSUE TITLE
Add blur

### ISSUE THREAD

**Issue by StarlkYT** [depressed-pho/natural-mystic-shaders#26] opened 2018-12-26 22:18 UTC
Add blur effect when the player come close to other objects

**Comment by depressed-pho** [comment] 2018-12-26 23:15
Do you mean depth-of-field effect? Then that's a duplicate of #4.
Or motion blur? Uhm that's impossible for the same reason why we can't do #4 atm.

**Closed by depressed-pho** 2018-12-26 23:15 UTC
